import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const file = join(here, "../ontology/core/extended-elements.json");
const elements = JSON.parse(readFileSync(file, "utf8"));
const existing = new Set(elements.map((e) => e.id));

const wave2 = [
  {
    id: "prompt-engineering",
    namespace: "core",
    name: "Prompt 工程",
    description: "Prompt 的层级、组装与管理：让指令结构化，而不是揉成一团",
    parentId: "harness",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: ["instruction-collision"],
    constraints: { requires: [], forbids: [], suggests: ["prompt-hierarchy"] },
    required: false,
    references: ["目录.md §3 Prompt Engineering"],
    version: "0.3.0",
    implementations: [{ name: "层级 + 组装两件套", note: "先声明优先级，再按来源组装" }],
    useCases: ["多来源指令（系统/开发者/用户/工具）共存的系统"],
    pros: ["指令冲突可预防", "Prompt 变更可管理"],
    cons: ["结构设计成本", "过度分层拖慢迭代"],
    commonIssues: ["指令优先级未声明导致冲突", "Prompt 膨胀"],
    relations: { allowedParents: ["harness"], allowedSiblings: ["context-engineering", "verification-gate"] },
  },
  {
    id: "prompt-hierarchy",
    namespace: "core",
    name: "Prompt 层级",
    description: "声明 system/developer/user/tool 等指令层级与冲突时的优先级",
    parentId: "prompt-engineering",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: ["instruction-collision"],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: [] },
    required: false,
    references: ["目录.md §3.1 Prompt 层级 / §3.5 Prompt Hierarchy"],
    version: "0.3.0",
    implementations: [
      { name: "显式优先级表", note: "system > developer > user，冲突时高优先级生效" },
      { name: "分区标记", note: "外部内容标记为不可信层，禁止覆盖指令层" },
    ],
    useCases: ["外部内容与指令同层的系统", "多开发者维护 Prompt 的团队"],
    pros: ["冲突裁决有据", "注入面收缩"],
    cons: ["层级设计争议", "过深层级难维护"],
    commonIssues: ["层级过多难以记忆", "优先级与实际组装顺序不一致"],
    relations: { allowedParents: ["prompt-engineering"], allowedSiblings: ["prompt-composition"] },
  },
  {
    id: "prompt-composition",
    namespace: "core",
    name: "Prompt 组装",
    description: "按来源与模板组装最终 Prompt：静态模板 / 动态组装 / 链式",
    parentId: "prompt-engineering",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {
      mode: { kind: "enum", values: ["static", "dynamic", "chained"], default: "static" },
    },
    mitigates: [],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: ["prompt-hierarchy"] },
    required: false,
    references: ["目录.md §3.3 Prompt 技术"],
    version: "0.3.0",
    implementations: [
      { name: "static", note: "固定模板，最简" },
      { name: "dynamic", note: "按任务/角色动态拼装片段" },
      { name: "chained", note: "多段 Prompt 链式传递" },
    ],
    useCases: ["多角色系统", "任务类型多样的平台"],
    pros: ["复用与一致性", "可按需注入上下文"],
    cons: ["组装逻辑成为故障点", "模板漂移"],
    commonIssues: ["Prompt 单体（全部揉在一起）", "动态片段顺序错误"],
    alternatives: ["static（最简）", "dynamic（按需拼装）", "chained（多段链路）"],
    relations: { allowedParents: ["prompt-engineering"], allowedSiblings: ["prompt-hierarchy"] },
  },
  {
    id: "pipeline",
    namespace: "core",
    name: "流水线拓扑",
    description: "Agent 按阶段串行交接，上游产出即下游输入，通信限于相邻阶段",
    parentId: "topology",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: ["communication-explosion"],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: [] },
    required: false,
    references: ["目录.md §13.1 Pipeline", "RAG 管线即典型流水线"],
    version: "0.3.0",
    implementations: [{ name: "阶段化交接", note: "每阶段契约化输入输出（配合组件契约）" }],
    useCases: ["步骤固定的处理链", "检索-生成类管线"],
    pros: ["通信复杂度 O(n)，无爆炸", "阶段可独立优化"],
    cons: ["错误沿链放大", "难以回退上游"],
    commonIssues: ["阶段间契约漂移", "错误级联"],
    alternatives: ["supervisor-worker（需要动态派发时）", "rag 模板（标准检索管线）"],
    relations: { allowedParents: ["topology"], allowedSiblings: ["supervisor-worker", "peer-to-peer", "hierarchical", "swarm"] },
  },
  {
    id: "swarm",
    namespace: "core",
    name: "群体拓扑",
    description: "大量同质 Agent 并行工作，无中心调度，靠局部规则协同",
    parentId: "topology",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: ["communication-explosion"],
    constraints: { requires: [], forbids: [], suggests: ["budget-caps"] },
    required: false,
    references: ["目录.md §13.1 Swarm"],
    version: "0.3.0",
    implementations: [{ name: "同质并行 + 结果聚合", note: "多实例同提示词并行，投票或择优" }],
    useCases: ["可大规模并行的探索任务", "多样性采样"],
    pros: ["吞吐高", "无单点"],
    cons: ["成本随数量线性增长", "全局一致性难保证"],
    commonIssues: ["代理数量失控", "重复产出"],
    alternatives: ["supervisor-worker（需要集中裁决时）"],
    relations: { allowedParents: ["topology"], allowedSiblings: ["supervisor-worker", "peer-to-peer", "hierarchical", "pipeline"] },
  },
  {
    id: "judge-role",
    namespace: "core",
    name: "Judge 角色",
    description: "对冲突的评审结论或多方产出做终审裁决的角色",
    parentId: "agents",
    allowMultiple: true,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: ["judge-bias"],
    constraints: { requires: [], forbids: [], suggests: ["reviewer-role"] },
    required: false,
    references: ["目录.md §13.2 Judge", "LLM-as-a-Judge"],
    version: "0.3.0",
    responsibilityTemplate: { owns: ["分歧裁决", "评审结论终审"], not: ["亲自修复产出", "任务分解"] },
    contractTemplate: {
      inputs: ["冲突的评审结论", "多方产出"],
      outputs: ["终审裁决（含理由）"],
      guarantees: ["裁决必须给出理由", "裁决为终局，不反复横跳"],
    },
    implementations: [
      { name: "LLM Judge", note: "用强模型做裁判，注意偏差校准" },
      { name: "规则裁决", note: "按预定义规则裁决（如测试通过率）" },
    ],
    useCases: ["辩论式推理", "多 Reviewer 意见冲突"],
    pros: ["分歧有终局", "质量闭环收口"],
    cons: ["Judge 自身有偏差", "增加一轮成本"],
    commonIssues: ["位置偏差/风格偏差", "Judge 与产出模型同源同错"],
    relations: { allowedParents: ["agents"] },
  },
  {
    id: "router-role",
    namespace: "core",
    name: "Router 角色",
    description: "对任务分类并路由到合适角色/模型的路由器角色",
    parentId: "agents",
    allowMultiple: true,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: ["model-routing"] },
    required: false,
    references: ["目录.md §13.2 Router", "Router-Agent Pattern"],
    version: "0.3.0",
    responsibilityTemplate: { owns: ["任务分类与分发", "目标角色/模型选择"], not: ["任务执行", "结果汇总"] },
    contractTemplate: {
      inputs: ["任务请求"],
      outputs: ["路由决策（目标与依据）"],
      guarantees: ["每个请求有且只有一个去向", "路由依据可追溯"],
    },
    implementations: [
      { name: "分类器路由", note: "小模型/规则先分类再分发" },
      { name: "语义相似度路由", note: "按任务嵌入匹配专家" },
    ],
    useCases: ["任务类型多样的入口", "专家团队协作"],
    pros: ["专家各司其职", "入口逻辑集中"],
    cons: ["误路由导致质量下降", "路由层延迟"],
    commonIssues: ["路由规则与能力清单漂移", "边界任务无明确去向"],
    relations: { allowedParents: ["agents"] },
  },
  {
    id: "monitor-role",
    namespace: "core",
    name: "Monitor 角色",
    description: "监督运行状态、检测异常与停滞、发出干预建议的角色",
    parentId: "agents",
    allowMultiple: true,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: ["trace"] },
    required: false,
    references: ["目录.md §13.2 Monitor"],
    version: "0.3.0",
    responsibilityTemplate: { owns: ["运行状态监督", "异常与停滞检测", "预算告警"], not: ["修复问题（转交执行角色）", "任务分解"] },
    contractTemplate: {
      inputs: ["执行轨迹与指标"],
      outputs: ["异常告警", "干预建议"],
      guarantees: ["只观测不改写执行状态", "告警附带证据（轨迹引用）"],
    },
    implementations: [
      { name: "轨迹审查者", note: "定期审查执行轨迹检测停滞" },
      { name: "预算哨兵", note: "监控花费与轮数阈值" },
    ],
    useCases: ["无人值守长任务", "多 Agent 系统运行监督"],
    pros: ["失控早发现", "干预有据"],
    cons: ["观测自身消耗上下文", "误报干扰"],
    commonIssues: ["告警阈值难定", "Monitor 与执行者职责混淆"],
    relations: { allowedParents: ["agents"] },
  },
  {
    id: "critic-role",
    namespace: "core",
    name: "Critic 角色",
    description: "对计划与过程挑错质疑的角色（区别于 Reviewer 的产出验收）",
    parentId: "agents",
    allowMultiple: true,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: ["plan-validation"] },
    required: false,
    references: ["目录.md §13.2 Critic", "Critic-Agent Pattern"],
    version: "0.3.0",
    responsibilityTemplate: { owns: ["过程与方向挑错", "方案可行性质疑"], not: ["产出验收（交给 Reviewer）", "亲自实现"] },
    contractTemplate: {
      inputs: ["计划与中间产出"],
      outputs: ["质疑清单", "改进方向"],
      guarantees: ["每条质疑给出具体依据", "质疑可被回应与关闭"],
    },
    implementations: [
      { name: "红队质疑", note: "专门寻找计划漏洞" },
      { name: "反思搭档", note: "与执行者配对做 Reflexion" },
    ],
    useCases: ["高风险决策前的方案审查", "Reflexion 循环"],
    pros: ["错误前置发现", "方案更健壮"],
    cons: ["过度质疑拖慢进度", "质疑质量依赖模型能力"],
    commonIssues: ["质疑空泛不可执行", "与 Reviewer 职责重叠"],
    relations: { allowedParents: ["agents"] },
  },
  {
    id: "procedural-memory",
    namespace: "core",
    name: "程序记忆",
    description: "怎么做的记忆：工具用法、技能套路、成功流程的可复用经验",
    parentId: "memory",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {},
    mitigates: [],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: [] },
    required: false,
    references: ["目录.md §5.1 Procedural Memory", "Voyager 技能库"],
    version: "0.3.0",
    implementations: [
      { name: "技能库", note: "成功流程沉淀为可调用技能" },
      { name: "工具用法档案", note: "记录工具调用的有效参数模式" },
    ],
    useCases: ["重复性子任务", "跨会话技能积累"],
    pros: ["经验复用降本", "新任务冷启动更快"],
    cons: ["陈旧套路误导", "技能库治理成本"],
    commonIssues: ["套路与当前环境不匹配", "技能冲突（同类任务多套路）"],
    alternatives: ["episodic-memory（时间线回忆）", "vector-memory（知识型记忆）"],
    relations: { allowedParents: ["memory"], allowedSiblings: ["episodic-memory", "vector-memory"] },
  },
  {
    id: "memory-consolidation",
    namespace: "core",
    name: "记忆整理",
    description: "记忆的衰减、归档、反思与摘要策略，防陈旧与膨胀",
    parentId: "memory",
    allowMultiple: false,
    extensionPoint: false,
    runtimeFamilies: "any",
    properties: {
      strategy: { kind: "enum", values: ["reflection", "decay", "archival", "summarization"], default: "reflection" },
    },
    mitigates: ["stale-memory"],
    introduces: [],
    constraints: { requires: [], forbids: [], suggests: [] },
    required: false,
    references: ["目录.md §5.4 Memory 策略", "Generative Agents 记忆反思"],
    version: "0.3.0",
    implementations: [
      { name: "reflection", note: "定期从记忆中提炼高层结论" },
      { name: "decay", note: "按重要度×时近性衰减淘汰" },
      { name: "archival", note: "冷记忆归档，按需找回" },
      { name: "summarization", note: "记忆簇摘要压缩" },
    ],
    useCases: ["长期运行系统", "记忆库持续增长的场景"],
    pros: ["记忆保鲜", "检索噪声下降"],
    cons: ["整理自身消耗算力", "误删有价值记忆"],
    commonIssues: ["衰减参数拍脑袋", "反思结论错误被固化"],
    alternatives: ["reflection（提炼型）", "decay（淘汰型）", "archival（归档型）", "summarization（压缩型）"],
    relations: { allowedParents: ["memory"], allowedSiblings: ["episodic-memory", "procedural-memory"] },
  },
];

let added = 0;
for (const el of wave2) {
  if (!existing.has(el.id)) {
    elements.push(el);
    added += 1;
  }
}
writeFileSync(file, JSON.stringify(elements, null, 2) + "\n");
console.log(`appended ${added} elements; total = ${elements.length}`);
